### ISSUE TITLE
App should run on iOS v.12

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer-mobile#10] opened 2022-01-29 19:49 UTC
Requested by @nimmolo. iOS v.12 is the highest version his iPhone will run.

**Comment by oliviacpu** [comment] 2022-02-04 19:49
I was able to install TestFlight and Mushroom Observer on my iPhone 6 running iOS 12.5.5.

The App Store allowed me to download an old version of TestFlight. I was able to install the test build and run it as expected after that.

It looks like our app is properly configured to run on iOS 12, but getting an older version of TestFlight might be the issue.

**Comment by nimmolo** [comment] 2022-02-04 22:08
Thanks Olivia -

How did you get Testflight to download on iOS 12.5.5? App Store (on iOS) is saying TF requires ioS 13 for me, no alternative given. I tried a “black market” app installer and the link was broken...

I haven’t installed TF previously, so i don’t have access to an older version via my account. (it seems TestFlight v.3 has been out since before your work started on the mobile app - so, out of reach)

Testflight also will not download on my Mac, which is on 10.14.6.

Any trick you found?

(Apple is getting so annoying! I’m sure i don’t know everything involved in keeping old software available, but blocking a working download doesn’t seem to be in anyone’s interest but theirs. Gr.)

Nimmo

**Comment by mo-nathan** [comment] 2024-02-22 11:52
@nimmolo Is this still an issue?  Can you get the current store version installed on your phone?

**Comment by mo-nathan** [comment] 2024-02-24 12:13
@nimmolo No longer has an iOS 12 device.  Not clear if the published app works and this was just a TestFlight issue.  Closing since we effectively cannot reproduce and we don't know of anyone who still cares.

**Closed by mo-nathan** 2024-02-24 12:13 UTC
Labels: enhancement, iOS
